//
//  Quote.swift
//  Outrageous Facts
//
//  Created by John Smith on 1/9/23.
//
// Should be populatedd by important historical facts that will make people better historians

import Foundation

struct Quote: Identifiable {
    let id: UUID
    var quote: String
    
    init(id: UUID = UUID(), quote: String) {
        self.id = id
        self.quote = quote
    }
}

extension Quote {
    static let sampleData: [Quote] =
    [
        Quote(quote: "Columbus sailed the ocean blue in 1492"),
        Quote(quote: "Tesla liked pigeons"),
        Quote(quote: "The Wright brothers originally worked on bicycles"),
        Quote(quote: "Galileo had two daughters and a son"),
        Quote(quote: "Marie Curie's daughter loved to play piano"),
        Quote(quote: "John D. Rockefeller had a goal to live to 100 years old"),
        Quote(quote: "The noncanonical Gospel of Thomas contains Jesus's sayings"),
        Quote(quote: "England and Zanzibar's war lasted 38 minutes"),
        Quote(quote: "Einstein declined becoming Israel's president in 1952"),
        Quote(quote: "Mona Lisa could be an anagram for Mon Salai"),
        Quote(quote: "Marie Curie is the first person to win the Nobel Prize twice"),
        Quote(quote: "Africa has never hosted an Olympics"),
        Quote(quote: "Lincoln established the Secret Service hours before being killed"),
        Quote(quote: "Marco Polo's story was written by a friend in jail"),
        Quote(quote: "Rockefeller founded the General Education Board"),
        Quote(quote: "Columbus reintroduced horses to North America in the 15th century"),
        Quote(quote: "The Tower of Pisa has been leaning for all its existence"),
        Quote(quote: "Tobacco was taken to Europe in 1528"),
        Quote(quote: "Mummification took 40 days to perform"),
        Quote(quote: "Ancient Egyptian shabtis were believed to serve the dead"),
        Quote(quote: "Frogs were a symbol of life and fertility in ancient Egypt"),
        Quote(quote: "Byzantines would sever people's noses to prevent them from ruling"),
        Quote(quote: "Jimmu, Japan's first emperor, was born in 660 BCE"),
        Quote(quote: "Catholics massacred around 15,000 Protestants in the 16th century"),
        Quote(quote: "Ghengis Khan means 'Universal Ruler'"),
        Quote(quote: "Tesla would have vivid visions of inventions"),
        Quote(quote: "Byzantines learned silk-making from two monks who smuggled silkworms"),
        Quote(quote: "Of the 70,000 rebels led by Spartacus, 6,000 were crucified"),
        Quote(quote: "Around 1 CE, the Roman Empire comprised 1/7 of the world's population"),
        Quote(quote: "Pope Leo III proclaimed Charlemagne king of the Holy Roman Empire"),
        Quote(quote: "Teotihuacan had 200,000 people at its peak"),
        Quote(quote: "In 125 CE, Chinese eunuchs murdered Emperor Shaodi"),
        Quote(quote: "The Roman military used thin wooden tablets for record-keeping"),
        Quote(quote: "Romans used metal strigils at their baths to help scrape off dirt"),
        Quote(quote: "Roman emperors were frequently murdered"),
        Quote(quote: "Emperor Ashoka's daughter spread Buddhism to Sri Lanka"),
        Quote(quote: "Between 235 and 284 CE, 25 different Roman emperors ruled"),
        Quote(quote: "Diocletian retired to his palace in Croatia in 305 and grew cabbages"),
        Quote(quote: "The Greek 'Chi-Rho' monogram was an important early Christian symbol"),
        Quote(quote: "Napoleon was attacked by bunnies"),
        Quote(quote: "Lincoln is in the wrestling hall of fame"),
        Quote(quote: "No witches were burned at the stake during the Salem witch trials"),
        Quote(quote: "Russia ran out of vodka at the end of WWII"),
        Quote(quote: "Tablecloths were designed to be a communal napkin"),
        Quote(quote: "The only WWII casualties on U.S. soil were from a Japanese balloon bomb"),
        Quote(quote: "Mary I was the first sole ruling queen of England"),
        Quote(quote: "The Doge of Venice was a title for the ruler of Venice"),
        Quote(quote: "Meriwether Lewis from Lewis and Clark had depression"),
        Quote(quote: "After Prince Albert died, Queen Victoria wore black every day"),
        Quote(quote: "Typhoons prevented the Mongols from invading Japan"),
        Quote(quote: "There were 8 Crusades"),
        Quote(quote: "Stephen Hawking was born exactly 300 years after Galileo died"),
        Quote(quote: "The Black Death killed 1/3 of the world's population"),
        Quote(quote: "The Pope could crown and uncrown emperors"),
        Quote(quote: "The first European settlement in North America was St. Augustine, FL in 1565"),
        Quote(quote: "Chlorine gas was used first by the Germans in 1915"),
        Quote(quote: "The Mongol Ruler Timur ruled an empire stretching from Syria to India"),
        Quote(quote: "In 1281, the Yuan Dynasty tried to conquer Japan with 3,500 ships"),
        Quote(quote: "In WWI, soldiers would sleep in trenches"),
        Quote(quote: "Lawrence of Arabia worked as a British intelligence officer in Cairo"),
        Quote(quote: "SALT I in 1972 was the first major US-USSR effort to scale back nuclear weapons"),
        Quote(quote: "In 1451, the Byzantine Empire was reduced to just the city of Constantinople"),
        Quote(quote: "Large mound sites in North America are attributed to the Adena and Hopewell people of 1000 BCE"),
        Quote(quote: "Around 2000 BCE, a stone called carnelian was valued second only to lapis lazuli"),
        Quote(quote: "The oldest stone tools are dated to 3.3 MYA"),
        Quote(quote: "The first human-like apes likely appeared 7-6 MYA"),
        Quote(quote: "Hominins left Africa 2 MYA"),
        Quote(quote: "The Homo habilis, the first member of our genus, appeared 2.5 MYA"),
        Quote(quote: "Humans first became establised in Africa around 300,000 BCE"),
        Quote(quote: "Visigoths sacked Rome in 410 and then agreed to work as Roman mercenaries"),
        Quote(quote: "Otto I was the first emperor of a clearly defined Holy Roman Empire"),
        Quote(quote: "The Holy Roman empire lasted for a little over a millennium"),
        Quote(quote: "Papal States were under the direct rule of the Pope"),
        Quote(quote: "The Ottoman Empire consumed most of Byzantine territory by the 1350s"),
        Quote(quote: "The Mongol prince Timur was angered by Ottoman demands in 1402 and invaded them"),
        Quote(quote: "Galileo became blind towards the end of his life"),
        Quote(quote: "Da Vinci conceptually invented the helicopter and parachute"),
        Quote(quote: "Slave trade was already abolished in Britain in 1807"),
        Quote(quote: "Both Britain and Russia failed to add Afghanistan to their empires"),
        Quote(quote: "Bastille was built as a Parisian fortress against the English in the 100 Years War"),
        Quote(quote: "Joan of Arc was only 19 when she relieved the siege of Orleans"),
        Quote(quote: "In 1405, a rare Chinese naval expedition was launched, reaching Africa and the Persian Gulf"),
        Quote(quote: "In 1428, Aztecs entered a Triple Alliance with two other city states, but dominated later on"),
        Quote(quote: "Peru's Chimu people were conquered by the Incas in 1470"),
        Quote(quote: "The Mwene Mutapa Empire of the 16th century dominated southeast Africa"),
        Quote(quote: "Only 21 of the original 180 Gutenberg Bibles exist today"),
        Quote(quote: "New Zealand's Maori culture was disrupted by Europeans arriving in 1642"),
        Quote(quote: "Ismail I founded the Safavid Dynasty which ruled Iran for 200 years starting in the 16th century"),
        Quote(quote: "90 percent of the New World population died from European diseases in the 16th century"),
        Quote(quote: "India's Mughal Empire was founded by Babur, a descendant of the Mongols"),
        Quote(quote: "China's Grand Canal was extended from Beijing to Huangzhou in 601-609 CE"),
        Quote(quote: "Buddhism was introduced to central China by Emperor Wu in 517 CE"),
        Quote(quote: "China's Grand Canal, at 1,104 miles, is the world's longest artificial waterway"),
        Quote(quote: "The Eastern Roman empire paid tributes to the Huns to prevent them from invading"),
        Quote(quote: "Theodosius I, the last west-east Roman emperor, made Christianity the official religion of the empire"),
        Quote(quote: "The Eiffel Tower was opened on the centenary of the French Revolution in 1889"),
        Quote(quote: "New Zealand was the first country to grant voting rights to women in 1893"),
        Quote(quote: "Kenneth I MacAlpin, the first king of the Scots, died of a tumor in 858"),
        Quote(quote: "Paris resisted a seige by tens of thousands of Vikings in 885-886"),
        Quote(quote: "Vietnam used to be under Chinese control until 938"),
        Quote(quote: "King Cnut of 11th century England paid 30,000 kg of silver to the Vikings to prevent attacks"),
        Quote(quote: "Hassan-i-Shabbah founded the Shia extremists' Assassins sect in 1094"),
        Quote(quote: "In 1077, Seleyman named his Sultanate 'Rum' because it sounded like 'Roman'"),
        Quote(quote: "English King Harold Godwinson fought two separate invasions 19 days apart in 1066"),
        Quote(quote: "Some ceramics in the Song Dynasty were so valued that they could be used to pay taxes"),
        Quote(quote: "Adolf Hitler tried to kill Churchhill by hiding a bomb inside chocolate"),
        Quote(quote: "One battle during the third Mithridatic War (74-70 BCE) ended when a meteor fell from the sky"),
        Quote(quote: "Claudette Colvin refused to move to the back of a segregated bus, 9 months before Rosa Parks's refusal"),
        Quote(quote: "Martin Luther King improvised the ending of 'I Have a Dream'"),
        Quote(quote: "Ancient Aztecs made necklaces out of popcorn"),
        Quote(quote: "Tutankhamen became ruler of ancient Egypt when he was just 9 years old"),
        Quote(quote: "Queen Elizabeth I invented gingerbread men"),
        Quote(quote: "Coca-Cola stopped containing cocaine in 1929"),
        Quote(quote: "King Louis IX tried to invade Egypt in 1248 but is defeated, captured, and ransomed"),
        Quote(quote: "Spain was the first to receive a commercial shipment of cacao beans from the New World in 1585"),
        Quote(quote: "The first compound optical mircoscope was invented by Dutch Zachiarias Janssen in 1590"),
        Quote(quote: "The most recent common ancestor of all humans is estimated to have lived during 170,000 BCE"),
        Quote(quote: "Fire is used in China in 500,000 BCE"),
        Quote(quote: "The earliest known heiroglyphic writing is the Narmer Palette of 3150 BCE"),
        Quote(quote: "3114 BCE is the first date in the Mayan Long Count Calendar"),
        Quote(quote: "The Chinchorro people of 5050 BCE Chile were the first culture known to mummify the dead"),
        Quote(quote: "The legendary Gilgamesh of Uruk lived around 2700 BCE"),
        Quote(quote: "Pharoh Khufu built the Great Pyramid of Giza in 2575 BCE"),
        Quote(quote: "The first documented conflict was between Sumerian city-states Lagash and Umma of 2450 BCE"),
        Quote(quote: "The Indus Valley city of Harappa had 25,000 people at its peak"),
        Quote(quote: "Assyria took over Babylon in 1220 BCE, ending a previous Kassite Dynasty rule of 350 years"),
        Quote(quote: "Pharaoh Akhenaten introduced monotheism for a god called Aten 1353-1336 BCE"),
        Quote(quote: "One of the largest chariot battles ever was between Hittite and Egyptian forces in 1274 BCE"),
        Quote(quote: "The Zhou dynasty of China was the longest lasting in Chinese history, ending in 1046 BCE"),
        Quote(quote: "The traditional date for the founding of Rome by Romulus is 753 BCE"),
        Quote(quote: "Solomon, king of Israel and son of David, ruled from 970-931 BCE"),
        Quote(quote: "Babylon was destroyed in 689 BCE by Sennacherib who broke down the walls and flooded its lands"),
        Quote(quote: "Sennacherib flooded Babylon by diverting entire canals"),
        Quote(quote: "Emperor Jimmu, first emperor of Japan, is said to be descended from the sun goddess Amaterasu"),
        Quote(quote: "Draco drafts Athen's first code of law in 621 BCE, known for the severity of its punishments"),
        Quote(quote: "The Kingdom of Judah fell in 609 BCE after King Josiah fell in battle against Pharaoh Necho II"),
        Quote(quote: "Lao Tzu, founder of Taoism, was born in 604 BCE, 1 year after the birth of Nebuchadnezzar II"),
        Quote(quote: "Only one of Greek poet Sappho's poems survives in its entirety: 'Ode to Aphrodite'"),
        Quote(quote: "The first coins ever minted were made by the Kingdom of Lydia in Anatolia in 650 BCE"),
        Quote(quote: "Greek philosopher Anaximander of the 6th century BCE theorized that life came from the oceans"),
        Quote(quote: "Rome's last king was named Tarquinius Superbus, crowned in 534 BCE"),
        Quote(quote: "Darius the Great brought the Persian Empire to its greatest extent from 522-486 BCE"),
        Quote(quote: "Democratic government was established in Athens in 507 BCE by Cleisthenes"),
        Quote(quote: "Zoroastrianism, a monotheistic religion founded by Zoroaster, was Persia's main religion in the 550s BCE"),
        Quote(quote: "The Delian League was founded by Athens in 478 BCE to counter Sparta's Peloponnesian League"),
        Quote(quote: "The Romans destroyed Carthage in 146 BCE, in perhaps the first genocide with 150,000 casualties"),
        Quote(quote: "Much of Jerusalem was destroyed by Romans in 70 CE after a Jewish revolt against Rome"),
        Quote(quote: "In 77 CE, Pliny the Elder started his 'Natural History', an encyclopedia on all knowledge"),
        Quote(quote: "The first seismometer was invented in China in 132 CE by Zhang Heng"),
        Quote(quote: "Galen, a physician to Roman emperors, had writings which influenced Western medical thinking for a millennia"),
        Quote(quote: "The first recorded invasion into Roman territory was in 238 by the Goth people"),
        Quote(quote: "Aksum in Ethiopia was the first African kingdom to adopt Christianity in 350 CE"),
        Quote(quote: "Christian beliefs were codified by the Council of Nicaea in 325"),
        Quote(quote: "Constantine had a vision of promised victory if 'Chi-Rho' was painted on his soldiers shields"),
        Quote(quote: "The Umayyad Caliphate had 29% of the world under its rule at its height, around 62 million people"),
        Quote(quote: "In 782, Charlemagne codified law which would perscribe death to anyone who wouldn't abandon paganism"),
        Quote(quote: "Tang Emperor Wuzong persecuted Buddhists in 842, perscribing the Manichaean faith instead"),
        Quote(quote: "The Goryeo Dynasty unified Korea in 918 and continued to rule for the next 400 years"),
        Quote(quote: "The last Viking king of York was named Eric Bloodaxe"),
        Quote(quote: "Lady Murasaki Shikibu's 'The Tale of Genji', known as the first novel, is written in Japan in 1020"),
        Quote(quote: "Catholic and Orthodox branches were formed after mutual excommunication in 1054"),
        Quote(quote: "The Taj Mahal was commissioned in 1634 by Shah Jahan in memory of his wife"),
        Quote(quote: "Spinoza and Locke, two great influencers of the Enlightenment, were both born in 1632"),
        Quote(quote: "Two men claimed to be the Pope in the Western Schism, which ended in 1417"),
        Quote(quote: "7 city council members were thrown out of a window in the 1419, sparking the Hussite Wars"),
        Quote(quote: "Lithuania resisted Christianity for a century before becoming Europe's last realm to convert in 1387"),
        Quote(quote: "China tried to conquer Dai Ngu (modern day Vietnam), but was defeated in 1424 by their leader, Le Loi"),
        Quote(quote: "An estimated 50 million people were killed by the Black Death in the 14th century"),
        Quote(quote: "60% of the world's silver came from Potosi, Bolivia in the late 16th century"),
        Quote(quote: "The French Wars of Religion claim around 3 million lives in the 16th century"),
        Quote(quote: "Japan tried to invade Korea in 1591 but China intervened and Korea fought back"),
        Quote(quote: "Japanese gold koban coins were oval shaped and were used from 1603-1888"),
        Quote(quote: "Modern day Manhattan Island, NY was purchased from the Lenape by the Dutch for just around $1000"),
        Quote(quote: "In 1629, King Charles dismissed the English parliament and ruled without it for 11 years"),
        Quote(quote: "The Great Fire of London destroyed 13,000 houses in 1666"),
        Quote(quote: "The Empire of Mali ruled west Africa for 400 years before falling in 1670"),
        Quote(quote: "The world's oldest bank, the Bank of Sweden, was founded in 1668"),
        Quote(quote: "China and Russia's border was determined by the Treaty of Nerchinsk in 1689"),
        Quote(quote: "The first women's magazine was published in London in 1693, but only ran for 4 weeks"),
        Quote(quote: "Mughal India began to decline in 1707 after the death of emperor Aurangzeb"),
        Quote(quote: "An alliance of pirates blocked Charleston, South Carolina in 1717 and demanded ransom"),
        Quote(quote: "China's 'Imperial Encyclopedia', completed in 1725, ended up being 10,000 volumes in length"),
        Quote(quote: "The first coffee plantation was made by the Portuguese in Brazil in 1727"),
        Quote(quote: "The first Europeans to see the Rocky Mountains were French brothers Luis and Francois de La Verendrye in 1743"),
        Quote(quote: "Benjamin Franklin invented the urinary catheter"),
        Quote(quote: "Britain responded to the Boston Tea Party with the 'Intolerable Acts' in 1774, which just led to more boycotting"),
        Quote(quote: "Tupac Amaru II, a descendant of the last Incan ruler, led an unsuccessful revolt against the Spanish in 1780-1782"),
        Quote(quote: "A secretive political and Bhuddhist movement called the White Lotus Rebellion fought the Qing Dynasty in 1796"),
        Quote(quote: "The first hot air balloon flight in 1783 lasted 10 minutes"),
        Quote(quote: "The Rosetta Stone was discovered by Napoleon's troops in Egypt in 1799"),
        Quote(quote: "During the War of 1812, the British set fire to the White House"),
        Quote(quote: "Napoleon ended hereditary nobility in Franch in 1804 with the Napoleonic Code"),
        Quote(quote: "Joseph Smith, the founder of Mormonism, claimed the Angel Moroni gave him visions in 1823"),
        Quote(quote: "China ceded five treaty ports as well as Hong Kong after losing the First Opium War in 1842"),
        Quote(quote: "Chloroform started being used as a medical anesthetic in 1841"),
        Quote(quote: "Ireland became severely depopulated after emigration during the Great Famine 1845-1854"),
        Quote(quote: "After gold was discovered in Australia in 1851, 500,000 immigrants arrived in the next 10 years"),
        Quote(quote: "After the Qing Dynasty is overthrown in 1911, China forms the new Chinese Republic"),
        Quote(quote: "Ford Motor Co. installs the first moving assembly line in 1913, and by 1927, there is 1 car for every 6 Americans"),
        Quote(quote: "The British Empire reaches its greatest extent in 1922, covering 1/4th of the world's land"),
        Quote(quote: "During America's US Dust Bowl, over 2.5 million people fled the Great Plains"),
        Quote(quote: "A prostitute in China named Ching Shih became one of the world's most successful pirates"),
        Quote(quote: "The Avengers were a group of Jewish assassins that poisoned Nazi war criminals after WWII"),
        Quote(quote: "The Olympics used to have fine arts competitions from 1912-1948"),
        Quote(quote: "The World Expo or the World Fair is held every 5 years"),
        Quote(quote: "Cleopatra was a descendant of the Macedonian general Ptolemy"),
        Quote(quote: "Ketchup used to be sold as a cure for an upset stomach in 1834"),
        Quote(quote: "Lincoln had around 300 wrestling matches and only lost 1"),
        Quote(quote: "George Washington's distillery was the largest in the US in 1799"),
        Quote(quote: "None of the accused were burned to death in the Salem witch trials"),
        Quote(quote: "The University of Oxford (1096) is older than the Aztec Empire (1325)"),
        Quote(quote: "In 18th century Europe, pineapples were a symbol of wealth, costing around $8000 each"),
        Quote(quote: "In ancient Rome, the most popular pets were dogs, ferrets, and monkeys"),
        Quote(quote: "Knocker-uppers were human alarm clocks during the Industrial Revolution in Britain"),
        Quote(quote: "For nearly 50 years, Denmark and Canada have fought over Hans Island (resolved 2022)"),
        Quote(quote: "Johnny Appleseed was a real person named John Chapman who introduced apple trees to parts of Pennsylvania"),
        Quote(quote: "European engineer Karl Benz patented the original automobile in 1886"),
        Quote(quote: "Some of the first responders to the Chernobyl nuclear disaster in 1986 died weeks later from radiation"),
        Quote(quote: "Nazi Germany's Master Interrogator, Hanns Scharff, interrogated by being as nice as possible"),
        Quote(quote: "Rome's first aqueduct was built by Appius Claudius in 312 BCE"),
        Quote(quote: "A Qiibla compass was to point to the direction of Mecca so worshippers could orient themselves for prayer"),
        Quote(quote: "Americans called hamburgers 'liberty steaks' because 'hamburger' sounded too German"),
        Quote(quote: "The Moche people engineered streams flowing down from the Andes into irrigation canals (100-600 CE)"),
        Quote(quote: "Pericles was the leader of Athens during the Peloponnesian War"),
        Quote(quote: "Sparta won the Peloponnesian War in 404 BCE"),
        Quote(quote: "Persia's King Darius invaded Greece in 492 BCE"),
        Quote(quote: "Xerxes I (486-465 BCE) was King Darius's son and successor"),
        Quote(quote: "Darius I was the third king of the Achaemenid Empire"),
        Quote(quote: "Darius I built Persepolis (around 500 BCE)"),
        Quote(quote: "The Persian empire invaded Greece in 492 and 480 BCE"),
        Quote(quote: "Athens and Eretria led a revolt against Persia's rule in 499 BCE, but Persia crushed the revolt"),
        Quote(quote: "Alexander III became king of Macedonia in 336 BCE"),
        Quote(quote: "Alexander the Great's father was killed by one of his bodyguards in 336 BCE"),
        Quote(quote: "Alexander the Great conquered the Achaemenid Dynasty of the Persian Empire in 327 BCE"),
        Quote(quote: "Alexander the Great's generals and associates were known as the Diadochi"),
        Quote(quote: "The Selucids, descendants of Alexander the Great's general Seleucus I Nicator, ruled lands from Persia to Thrace"),
        Quote(quote: "Alexander the Great's general Antigonus took over Macedonia and parts of Greece"),
        Quote(quote: "Alexander the Great wanted to conquer India but his troops were too tired to continue"),
        Quote(quote: "The Greek Archaic Period was during 800-479 BCE"),
        Quote(quote: "Rome's first Emperor in 31 BCE was originally named Octavian but then took the title Caesar Augustus"),
        Quote(quote: "Mount Vesuvius erupted in 79 CE, devastating Pompeii"),
        Quote(quote: "Roman Emperor Diocletian split the Empire in two in 285 CE"),
        Quote(quote: "The Eruscans were one of the most influential societies in the Mediterranean until being absorbed by Rome"),
        Quote(quote: "Southern Italy in 700-250 BCE was referred to as Magna Graecia because the Greek presence was so strong"),
        Quote(quote: "Romans took over Magna Graecia in Southern Italy in the 3rd century BCE"),
        Quote(quote: "Legend says Rome was founded by Romulus and Remus in 753 BCE"),
        Quote(quote: "Rome became a republic in 509 BCE"),
        Quote(quote: "There were three Punic wars between the Romans and Carthaginians"),
        Quote(quote: "Hannibal's army was said to have 37 war elephants in the Second Punic War"),
        Quote(quote: "During the "),
        Quote(quote: "Augustus made the Greek city of Ephesus the capital of Asia in 27 BCE"),
        Quote(quote: "Octavian defeated Mark Antony and Cleopatra in the Battle of Actium in 31 BCE"),
        Quote(quote: "The word Vedas (Indo-Aryan's sacred text) is the Sanskrit word for knowledge"),
        Quote(quote: "India's caste system combosed of priests, warriors, traders, and servants"),
        Quote(quote: "The Buddha was born in Lumbini in Northern India in 563 or 480 BCE"),
        Quote(quote: "After the conquest of Kalinga in 261 BCE, the Mauryan India emperor Ashoka converted to Buddhism"),
        Quote(quote: "The Mauryan Empire, India's largest empire, was founded by Chandragupta Maurya in 321 BCE"),
        Quote(quote: "The Qin state defeated the other Warring States in 350 BCE"),
        Quote(quote: "China's emperor Qin Shi Huang establshes Xianyang as its capital in 221 BCE"),
        Quote(quote: "Qin Shi Huang abolished feudalism in 221 BCE"),
        Quote(quote: "Qin Shi Huang started ordering the construction of the Great Wall in 218 BCE")
    ]
}
