//
//  Quote.swift
//  Outrageous Facts
//
//  Created by John Smith on 1/9/23.
//

import Foundation

struct Quote: Identifiable {
    let id: UUID
    var quote: String
    
    init(id: UUID = UUID(), quote: String) {
        self.id = id
        self.quote = quote
    }
}

extension Quote {
    static let sampleData: [Quote] =
    [
        Quote(quote: "Columbus sailed the ocean blue in 1492"),
        Quote(quote: "Tesla liked pigeons"),
        Quote(quote: "The Wright brothers originally worked on bicycles"),
        Quote(quote: "Galileo had two daughters and a son"),
        Quote(quote: "Marie Curie's daughter loved to play piano"),
        Quote(quote: "John D. Rockefeller had a goal to live to 100 years old"),
        Quote(quote: "The noncanonical Gospel of Thomas contains Jesus's sayings"),
        Quote(quote: "England and Zanzibar's war lasted 38 minutes"),
        Quote(quote: "Einstein declined becoming Israel's president in 1952"),
        Quote(quote: "Mona Lisa could be an anagram for Mon Salai"),
        Quote(quote: "Marie Curie is the first person to win the Nobel Prize twice"),
        Quote(quote: "Africa has never hosted an Olympics"),
        Quote(quote: "Lincoln established the Secret Service hours before being killed"),
        Quote(quote: "Marco Polo's story was written by a friend in jail"),
        Quote(quote: "Rockefeller founded the General Education Board"),
        Quote(quote: "Columbus reintroduced horses to North America in the 15th century"),
        Quote(quote: "The Tower of Pisa has been leaning for all its existence"),
        Quote(quote: "Tobacco was taken to Europe in 1528"),
        Quote(quote: "Mummification took 40 days to perform"),
        Quote(quote: "Ancient Egyptian shabtis were believed to serve the dead"),
        Quote(quote: "Frogs were a symbol of life and fertility in ancient Egypt"),
        Quote(quote: "Byzantines would sever people's noses to prevent them from ruling"),
        Quote(quote: "Jimmu, Japan's first emperor, was born in 660 BCE"),
        Quote(quote: "Catholics massacred around 15,000 Protestants in the 16th century"),
        Quote(quote: "Ghengis Khan means 'Universal Ruler'"),
        Quote(quote: "Tesla would have vivid visions of inventions"),
        Quote(quote: "Byzantines learned silk-making from two monks who smuggled silkworms"),
        Quote(quote: "Of the 70,000 rebels led by Spartacus, 6,000 were crucified"),
        Quote(quote: "Around 1 CE, the Roman Empire comprised 1/7 of the world's population"),
        Quote(quote: "Pope Leo III proclaimed Charlemagne king of the Holy Roman Empire"),
        Quote(quote: "Teotihuacan had 200,000 people at its peak"),
        Quote(quote: "In 125 CE, Chinese eunuchs murdered Emperor Shaodi"),
        Quote(quote: "The Roman military used thin wooden tablets for record-keeping"),
        Quote(quote: "Romans used metal strigils at their baths to help scrape off dirt"),
        Quote(quote: "Roman emperors were frequently murdered"),
        Quote(quote: "Emperor Ashoka's daughter spread Buddhism to Sri Lanka"),
        Quote(quote: "Between 235 and 284 CE, 25 different Roman emperors ruled"),
        Quote(quote: "Diocletian retired to his palace in Croatia in 305 and grew cabbages"),
        Quote(quote: "The Greek 'Chi-Rho' monogram was an important early Christian symbol"),
        Quote(quote: "Napoleon was attacked by bunnies"),
        Quote(quote: "Lincoln is in the wrestling hall of fame"),
        Quote(quote: "No witches were burned at the stake during the Salem witch trials"),
        Quote(quote: "Russia ran out of vodka at the end of WWII"),
        Quote(quote: "Tablecloths were designed to be a communal napkin"),
        Quote(quote: "The only WWII casualties on U.S. soil were from a Japanese balloon bomb"),
        Quote(quote: "Mary I was the first sole ruling queen of England"),
        Quote(quote: "The Doge of Venice was a title for the ruler of Venice"),
        Quote(quote: "Meriwether Lewis from Lewis and Clark had depression"),
        Quote(quote: "After Prince Albert died, Queen Victoria wore black every day"),
        Quote(quote: "Typhoons prevented the Mongols from invading Japan"),
        Quote(quote: "There were 8 Crusades"),
        Quote(quote: "Stephen Hawking was born exactly 300 years after Galileo died"),
        Quote(quote: "The Black Death killed 1/3 of the world's population"),
        Quote(quote: "The Pope could crown and uncrown emperors"),
        Quote(quote: "The first European settlement in North America was St. Augustine, FL in 1565"),
        Quote(quote: "Chlorine gas was used first by the Germans in 1915"),
        Quote(quote: "The Mongol Ruler Timur ruled an empire stretching from Syria to India"),
        Quote(quote: "In 1281, the Yuan Dynasty tried to conquer Japan with 3,500 ships"),
        Quote(quote: "In WWI, soldiers would sleep in trenches"),
        Quote(quote: "Lawrence of Arabia worked as a British intelligence officer in Cairo"),
        Quote(quote: "SALT I in 1972 was the first major US-USSR effort to scale back nuclear weapons"),
        Quote(quote: "In 1451, the Byzantine Empire was reduced to just the city of Constantinople"),
        Quote(quote: "Large mound sites in North America are attributed to the Adena and Hopewell people of 1000 BCE"),
        Quote(quote: "Around 2000 BCE, a stone called carnelian was valued second only to lapis lazuli"),
        Quote(quote: "The oldest stone tools are dated to 3.3 MYA"),
        Quote(quote: "The first human-like apes likely appeared 7-6 MYA"),
        Quote(quote: "Hominins left Africa 2 MYA"),
        Quote(quote: "The Homo habilis, the first member of our genus, appeared 2.5 MYA"),
        Quote(quote: "Humans first became establised in Africa around 300,000 BCE"),
        Quote(quote: "Visigoths sacked Rome in 410 and then agreed to work as Roman mercenaries"),
        Quote(quote: "Otto I was the first emperor of a clearly defined Holy Roman Empire"),
        Quote(quote: "The Holy Roman empire lasted for a little over a millennium"),
        Quote(quote: "Papal States were under the direct rule of the Pope"),
        Quote(quote: "The Ottoman Empire consumed most of Byzantine territory by the 1350s"),
        Quote(quote: "The Mongol prince Timur was angered by Ottoman demands in 1402 and invaded them"),
        Quote(quote: "Galileo became blind towards the end of his life"),
        Quote(quote: "Da Vinci conceptually invented the helicopter and parachute"),
        Quote(quote: "Slave trade was already abolished in Britain in 1807"),
        Quote(quote: "Both Britain and Russia failed to add Afghanistan to their empires"),
        Quote(quote: "Bastille was built as a Parisian fortress against the English in the 100 Years War"),
        Quote(quote: "Joan of Arc was only 19 when she relieved the siege of Orleans"),
        Quote(quote: "In 1405, a rare Chinese naval expedition was launched, reaching Africa and the Persian Gulf"),
        Quote(quote: "In 1428, Aztecs entered a Triple Alliance with two other city states, but dominated later on"),
        Quote(quote: "Peru's Chimu people were conquered by the Incas in 1470"),
        Quote(quote: "The Mwene Mutapa Empire of the 16th century dominated southeast Africa"),
        Quote(quote: "Only 21 of the original 180 Gutenberg Bibles exist today"),
        Quote(quote: "New Zealand's Maori culture was disrupted by Europeans arriving in 1642"),
        Quote(quote: "Ismail I founded the Safavid Dynasty which ruled Iran for 200 years starting in the 16th century"),
        Quote(quote: "90 percent of the New World population died from European diseases in the 16th century"),
        Quote(quote: "India's Mughal Empire was founded by Babur, a descendant of the Mongols"),
        Quote(quote: "China's Grand Canal was extended from Beijing to Huangzhou in 601-609 CE"),
        Quote(quote: "Buddhism was introduced to central China by Emperor Wu in 517 CE"),
        Quote(quote: "China's Grand Canal, at 1,104 miles, is the world's longest artificial waterway"),
        Quote(quote: "The Eastern Roman empire paid tributes to the Huns to prevent them from invading"),
        Quote(quote: "Theodosius I, the last west-east Roman emperor, made Christianity the official religion of the empire"),
        Quote(quote: "The Eiffel Tower was opened on the centenary of the French Revolution in 1889"),
        Quote(quote: "New Zealand was the first country to grant voting rights to women in 1893"),
        Quote(quote: "Kenneth I MacAlpin, the first king of the Scots, died of a tumor in 858"),
        Quote(quote: "Paris resisted a seige by tens of thousands of Vikings in 885-886"),
        Quote(quote: "Vietnam used to be under Chinese control until 938"),
        Quote(quote: "King Cnut of 11th century England paid 30,000 kg of silver to the Vikings to prevent attacks"),
        Quote(quote: "Hassan-i-Shabbah founded the Shia extremists' Assassins sect in 1094"),
        Quote(quote: "In 1077, Seleyman named his Sultanate 'Rum' because it sounded like 'Roman'"),
        Quote(quote: "English King Harold Godwinson fought two separate invasions 19 days apart in 1066"),
        Quote(quote: "Some ceramics in the Song Dynasty were so valued that they could be used to pay taxes"),
        Quote(quote: "Adolf Hitler tried to kill Churchhill by hiding a bomb inside chocolate"),
        Quote(quote: "One battle during the third Mithridatic War (74-70 BCE) ended when a meteor fell from the sky"),
        Quote(quote: "Claudette Colvin refused to move to the back of a segregated bus, 9 months before Rosa Parks's refusal"),
        Quote(quote: "Martin Luther King improvised the ending of 'I Have a Dream'"),
        Quote(quote: "Ancient Aztecs made necklaces out of popcorn"),
        Quote(quote: "Tutankhamen became ruler of ancient Egypt when he was just 9 years old"),
        Quote(quote: "Queen Elizabeth I invented gingerbread men"),
        Quote(quote: "Coca-Cola stopped containing cocaine in 1929"),
        Quote(quote: "King Louis IX tried to invade Egypt in 1248 but is defeated, captured, and ransomed"),
        Quote(quote: "Spain was the first to receive a commercial shipment of cacao beans from the New World in 1585"),
        Quote(quote: "The first compound optical mircoscope was invented by Dutch Zachiarias Janssen in 1590"),
        Quote(quote: "The most recent common ancestor of all humans is estimated to have lived during 170,000 BCE"),
        Quote(quote: "Fire is used in China in 500,000 BCE"),
        Quote(quote: "The earliest known heiroglyphic writing is the Narmer Palette of 3150 BCE"),
        Quote(quote: "3114 BCE is the first date in the Mayan Long Count Calendar"),
        Quote(quote: "The Chinchorro people of 5050 BCE Chile were the first culture known to mummify the dead"),
        Quote(quote: "The legendary Gilgamesh of Uruk lived around 2700 BCE"),
        Quote(quote: "Pharoh Khufu built the Great Pyramid of Giza in 2575 BCE"),
        Quote(quote: "The first documented conflict was between Sumerian city-states Lagash and Umma of 2450 BCE"),
        Quote(quote: "The Indus Valley city of Harappa had 25,000 people at its peak"),
        Quote(quote: "Assyria took over Babylon in 1220 BCE, ending a previous Kassite Dynasty rule of 350 years"),
        Quote(quote: "Pharaoh Akhenaten introduced monotheism for a god called Aten 1353-1336 BCE"),
        Quote(quote: "One of the largest chariot battles ever was between Hittite and Egyptian forces in 1274 BCE"),
        Quote(quote: "The Zhou dynasty of China was the longest lasting in Chinese history, ending in 1046 BCE"),
        Quote(quote: "The traditional date for the founding of Rome by Romulus is 753 BCE"),
        Quote(quote: "Solomon, king of Israel and son of David, ruled from 970-931 BCE"),
        Quote(quote: "Babylon was destroyed in 689 BCE by Sennacherib who broke down the walls and flooded its lands"),
        Quote(quote: "Sennacherib flooded Babylon by diverting entire canals"),
        Quote(quote: "Emperor Jimmu, first emperor of Japan, is said to be descended from the sun goddess Amaterasu"),
        Quote(quote: "Draco drafts Athen's first code of law in 621 BCE, known for the severity of its punishments"),
        Quote(quote: "The Kingdom of Judah fell in 609 BCE after King Josiah fell in battle against Pharaoh Necho II"),
        Quote(quote: "Lao Tzu, founder of Taoism, was born in 604 BCE, 1 year after the birth of Nebuchadnezzar II"),
        Quote(quote: "Only one of Greek poet Sappho's poems survives in its entirety: 'Ode to Aphrodite'"),
        Quote(quote: "The first coins ever minted were made by the Kingdom of Lydia in Anatolia in 650 BCE"),
        Quote(quote: "Greek philosopher Anaximander of the 6th century BCE theorized that life came from the oceans"),
        Quote(quote: "Rome's last king was named Tarquinius Superbus, crowned in 534 BCE"),
        Quote(quote: "Darius the Great brought the Persian Empire to its greatest extent from 522-486 BCE"),
        Quote(quote: "Democratic government was established in Athens in 507 BCE by Cleisthenes"),
        Quote(quote: "Zoroastrianism, a monotheistic religion founded by Zoroaster, was Persia's main religion in the 550s BCE"),
        Quote(quote: "The Delian League was founded by Athens in 478 BCE to counter Sparta's Peloponnesian League"),
        Quote(quote: "The Romans destroyed Carthage in 146 BCE, in perhaps the first genocide with 150,000 casualties"),
        Quote(quote: "Much of Jerusalem was destroyed by Romans in 70 CE after a Jewish revolt against Rome"),
        Quote(quote: "In 77 CE, Pliny the Elder started his 'Natural History', an encyclopedia on all knowledge"),
        Quote(quote: "The first seismometer was invented in China in 132 CE by Zhang Heng"),
        Quote(quote: "Galen, a physician to Roman emperors, had writings which influenced Western medical thinking for a millennia"),
        Quote(quote: "The first recorded invasion into Roman territory was in 238 by the Goth people"),
        Quote(quote: "Aksum in Ethiopia was the first African kingdom to adopt Christianity in 350 CE"),
        Quote(quote: "Christian beliefs were codified by the Council of Nicaea in 325"),
        Quote(quote: "Constantine had a vision of promised victory if 'Chi-Rho' was painted on his soldiers shields")
    ]
}
